version: "3.7"

networks:
  web:
    external: yes

services:
  
  flask:
    build: .
    restart: always
    volumes:
      - ./web:/app
    networks:
      - web
    # command: /usr/local/bin/gunicorn app:app -w 1 -b :5000 --reload --timeout 600
    command: flask run --host 0.0.0.0

  nginx:
    restart: always
    build: ./nginx/
    volumes:
      - ./web:/app
    links:
      - flask:flask
    networks:
      - web
    labels:
      - "traefik.backend=aro.ovh.catalog"
      - "traefik.frontend.rule=Host:aro-catalog.local"
      - "traefik.frontend.entrypoints=http"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.default.protocol=http"
