version: "3.7"

networks:
  web:
    external: yes

services:
  flask:
    build: .
    restart: always
    networks:
      - web
    volumes:
      - ./web:/app
    ports:
      - "8080:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: flask run --host 0.0.0.0
